<?php

/**
 * @file
 * Giphy Search module code.
 */

/**
 * Implements hook_menu().
 */
function giphy_search_menu() {
  $items['giphy-search'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Giphy Search',
    'description' => 'Configure Giphy integration settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('giphy_search_search_form'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Giphy Search form.
 */
function giphy_search_search_form($form, &$form_state) {
  $form['#id'] = drupal_html_id('giphy_search_form');
  $form['#type'] = 'fieldset';

  $search = (isset($form_state['input']['keywords'])) ? $form_state['input']['keywords'] : NULL;

  $form['giphy_search']['keywords'] = array(
    '#type' => 'textfield',
    '#title' => t('Search Giphy content'),
    '#placeholder' => t('Enter your search text here'),
  );

  $form['giphy_search']['search'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#action' => 'search',
    '#name' => drupal_html_id('giphy_search'),
  );


  $form['giphy_search']['results'] = array(
    '#theme' => 'table',
  );

  $header = array(t('GIF'), t('ID'), t('Embded URL'), t('Source'), t('Rating'));

  if ($search) {

    $header = array(t('GIF'), t('ID'), t('Embed URL'), t('Source'), t('Rating'));

    $matches = giphy_search($search);
    $rows = array();
    foreach ($matches as $giphy) {
      $row = array();
      $gif = array();

      $gif['#theme'] = 'giphy';
      $gif['#giphy'] = $giphy;
      $gif['#image'] = 'fixed_height_small_still';

      $row[] = drupal_render($gif);
      $row[] = $giphy->id;
      $row[] = $giphy->embed_url;
      $row[] = $giphy->source;
      $row[] = $giphy->rating;

      $rows[] = $row;
    }

    $form['giphy_search']['results']['#header'] = $header;
    $form['giphy_search']['results']['#rows'] =   $rows;

  }
  return $form;
}

function giphy_search_search_form_submit($form, &$form_state) {
  $keywords = filter_xss($form_state['values']['keywords']);
  if (!empty($keywords)) {
  	drupal_set_message(t('You searched for ' . $keywords));
  	$form_state['rebuild'] = TRUE;
  }
}
